#!/usr/bin/env bash
# WorkBrain GCP Setup Script
# Updated for existing instance: csql-workbrain
# Creates: database 'workbrain', user 'workbrain_user', applies schema to workbrain_schema
#
# Run ONCE:  chmod +x setup_gcp.sh && ./setup_gcp.sh
set -euo pipefail

# ── EDIT THESE ────────────────────────────────────────────────────────────────
PROJECT_ID="project-901e5f96-55af-4675-abe"          
REGION="us-central1"
DB_INSTANCE="csql-workbrain"             
DB_NAME="workbrain"
DB_SCHEMA="workbrain_schema"
DB_USER="workbrain_user"
DB_PASSWORD="password"              # ← change to a strong password
ADMIN_PASSWORD="postgres-admin-pw"  # ← postgres superuser password (for schema setup only)
# ── END EDIT ──────────────────────────────────────────────────────────────────

SA_EMAIL="workbrain-sa@${PROJECT_ID}.iam.gserviceaccount.com"
INSTANCE_CONN="${PROJECT_ID}:${REGION}:${DB_INSTANCE}"

echo "=== WorkBrain GCP Setup ==="
echo "  Project  : $PROJECT_ID"
echo "  Instance : $DB_INSTANCE  (existing — will NOT recreate)"
echo "  Database : $DB_NAME"
echo "  Schema   : $DB_SCHEMA"
echo "  App user : $DB_USER"
echo ""

gcloud config set project "$PROJECT_ID"

# ── 1. Enable APIs ────────────────────────────────────────────────────────────
echo "Step 1: Enabling APIs..."
gcloud services enable \
  run.googleapis.com \
  sqladmin.googleapis.com \
  aiplatform.googleapis.com \
  secretmanager.googleapis.com \
  cloudbuild.googleapis.com \
  artifactregistry.googleapis.com \
  calendar-json.googleapis.com \
  tasks.googleapis.com \
  --quiet
echo "✓ APIs enabled"

# ── 2. Service Account ────────────────────────────────────────────────────────
echo "Step 2: Service account..."
gcloud iam service-accounts create workbrain-sa \
  --display-name="WorkBrain SA" --quiet 2>/dev/null || echo "  (already exists)"

for ROLE in \
  roles/aiplatform.user \
  roles/cloudsql.client \
  roles/secretmanager.secretAccessor \
  roles/run.invoker; do
  gcloud projects add-iam-policy-binding "$PROJECT_ID" \
    --member="serviceAccount:${SA_EMAIL}" --role="$ROLE" --quiet
done

gcloud iam service-accounts keys create ./backend/service-account.json \
  --iam-account="$SA_EMAIL" --quiet
echo "✓ Service account ready | key: backend/service-account.json"

# ── 3. Create database (if not exists) ───────────────────────────────────────
echo "Step 3: Creating database '$DB_NAME' on instance '$DB_INSTANCE'..."
gcloud sql databases create "$DB_NAME" \
  --instance="$DB_INSTANCE" --quiet 2>/dev/null || echo "  (database already exists)"
echo "✓ Database: $DB_NAME"

# ── 4. Create workbrain_user ──────────────────────────────────────────────────
# echo "Step 4: Creating database user '$DB_USER'..."
# gcloud sql users create "$DB_USER" \
#   --instance="$DB_INSTANCE" \
#   --password="$DB_PASSWORD" \
#   --quiet 2>/dev/null || \
# gcloud sql users set-password "$DB_USER" \
#   --instance="$DB_INSTANCE" \
#   --password="$DB_PASSWORD" \
#   --quiet
# echo "✓ User $DB_USER created/updated"

# ── 5. Store password in Secret Manager ──────────────────────────────────────
echo "Step 5: Storing secrets..."
echo -n "$DB_PASSWORD" | gcloud secrets create workbrain-db-password \
  --data-file=- --quiet 2>/dev/null || \
echo -n "$DB_PASSWORD" | gcloud secrets versions add workbrain-db-password \
  --data-file=- --quiet

DB_URL="postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@/${DB_NAME}?host=/cloudsql/${INSTANCE_CONN}&options=-csearch_path%3D${DB_SCHEMA}"
echo -n "$DB_URL" | gcloud secrets create workbrain-db-url \
  --data-file=- --quiet 2>/dev/null || \
echo -n "$DB_URL" | gcloud secrets versions add workbrain-db-url \
  --data-file=- --quiet
echo "✓ Secrets stored in Secret Manager"

# ── 6. Artifact Registry ──────────────────────────────────────────────────────
echo "Step 6: Artifact Registry..."
gcloud artifacts repositories create workbrain \
  --repository-format=docker --location="$REGION" --quiet 2>/dev/null || \
  echo "  (already exists)"
echo "✓ Artifact Registry: ${REGION}-docker.pkg.dev/${PROJECT_ID}/workbrain"

# ── 7. Write .env ──────────────────────────────────────────────────────────────
echo "Step 7: Writing backend/.env..."
cat > ./backend/.env << ENV
# Auto-generated by setup_gcp.sh
GCP_PROJECT_ID=${PROJECT_ID}
GCP_REGION=${REGION}

# Local dev (via Cloud SQL Proxy):
DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}
CLOUD_SQL_INSTANCE=${INSTANCE_CONN}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=${DB_NAME}
DB_SCHEMA=${DB_SCHEMA}

VERTEX_AI_MODEL=gemini-2.0-flash-001
VERTEX_AI_LOCATION=${REGION}
APP_ENV=development
USER_ID=demo_user
DAILY_CAPACITY_MINUTES=480
OVERLOAD_THRESHOLD=0.85
FRONTEND_URL=http://localhost:3000
ENV
echo "✓ backend/.env written"

# ── 8. Download Cloud SQL Proxy ───────────────────────────────────────────────
if [ ! -f "./cloud-sql-proxy" ]; then
  echo "Step 8: Downloading Cloud SQL Proxy..."
  curl -sSo cloud-sql-proxy \
    "https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.8.0/cloud-sql-proxy.linux.amd64"
  chmod +x cloud-sql-proxy
  echo "✓ cloud-sql-proxy downloaded"
else
  echo "Step 8: Cloud SQL Proxy already present"
fi

# ── 9. Apply schema ───────────────────────────────────────────────────────────
echo ""
echo "Step 9: Applying schema..."
echo "  Starting Cloud SQL Proxy for schema setup..."
./cloud-sql-proxy "${INSTANCE_CONN}" --port=5433 &
PROXY_PID=$!
sleep 4

echo "  Running schema.sql as postgres superuser..."
PGPASSWORD="$ADMIN_PASSWORD" psql \
  -h 127.0.0.1 -p 5433 \
  -U postgres \
  -d "$DB_NAME" \
  -f ./scripts/schema.sql \
  && echo "✓ Schema applied: workbrain_schema + 4 tables + workbrain_user grants" \
  || echo "  ⚠ Schema failed. Run manually — see instructions below."

kill $PROXY_PID 2>/dev/null || true

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "=========================================="
echo "  WorkBrain GCP setup complete!"
echo "=========================================="
echo ""
echo "To run locally:"
echo ""
echo "  Terminal 1 — Cloud SQL Proxy:"
echo "    ./cloud-sql-proxy ${INSTANCE_CONN} --port=5432"
echo ""
echo "  Terminal 2 — Backend:"
echo "    cd backend"
echo "    python -m venv venv && source venv/bin/activate"
echo "    pip install -r requirements.txt"
echo "    export GOOGLE_APPLICATION_CREDENTIALS=./service-account.json"
echo "    uvicorn main:app --reload --port 8080"
echo ""
echo "  Terminal 3 — Test:"
echo "    python scripts/test_e2e.py"
echo ""
echo "If schema step failed, run manually:"
echo "  ./cloud-sql-proxy ${INSTANCE_CONN} --port=5433 &"
echo "  PGPASSWORD=<ADMIN_PW> psql -h 127.0.0.1 -p 5433 -U postgres -d $DB_NAME -f scripts/schema.sql"
